# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ana_pencere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 477)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 611, 351))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.btnHastaEkle = QtWidgets.QPushButton(self.centralwidget)
        self.btnHastaEkle.setGeometry(QtCore.QRect(20, 380, 75, 23))
        self.btnHastaEkle.setObjectName("btnHastaEkle")
        self.btnHastaGuncelle = QtWidgets.QPushButton(self.centralwidget)
        self.btnHastaGuncelle.setGeometry(QtCore.QRect(180, 380, 75, 23))
        self.btnHastaGuncelle.setObjectName("btnHastaGuncelle")
        self.btnHastaSil = QtWidgets.QPushButton(self.centralwidget)
        self.btnHastaSil.setGeometry(QtCore.QRect(100, 380, 75, 23))
        self.btnHastaSil.setObjectName("btnHastaSil")
        self.btnDetayGoster = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetayGoster.setGeometry(QtCore.QRect(554, 400, 71, 21))
        self.btnDetayGoster.setObjectName("btnDetayGoster")
        self.btnAnket = QtWidgets.QPushButton(self.centralwidget)
        self.btnAnket.setGeometry(QtCore.QRect(480, 400, 71, 21))
        self.btnAnket.setObjectName("btnAnket")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TC"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Soyad"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Doğum Tarihi"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Servis"))
        self.btnHastaEkle.setText(_translate("MainWindow", "Ekle"))
        self.btnHastaGuncelle.setText(_translate("MainWindow", "Güncelle"))
        self.btnHastaSil.setText(_translate("MainWindow", "Sil"))
        self.btnDetayGoster.setText(_translate("MainWindow", "Detay"))
        self.btnAnket.setText(_translate("MainWindow", "Anket"))
